### PR TITLE
mass changes in function input

### PR DESCRIPTION
**Pull request by rogerzou**
Improve function inputs
update README
run alignmenttests on matlab to test

### CODE REVIEW

**Comment by wrgr** [comment]
@Roger, Julie: I brought you back unaligned data from Wei last week.  2TB
at JHU - we need to find a way for you to get it.  :)

Best,
Will

**Comment by rogerzou** [comment]
it would be great if the unaligned data could be on the API for us to test.
All the functions we talked about when you came over are implemented, and
to my knowledge work. However, this unaligned data would be a good way to
verify that because lee14 and kasthuri11cc seem aligned very well already.

Thanks,
Roger

**Comment by wrgr** [comment]
Yah - can you get in touch with Kunal?  There's not a great way to ingest
it into the API - because Kunal is busy with other things and it's hard to
say what the right way to do the ingest is...meaning it is unclear (to me)
what coordinates we should use for unaligned data.

In any case, a fast answer is to have Kunal host somewhere on a machine
where you can pull down data via FTP.  Data can be read into matlab with
imread and converted to a RAMONVolume (for use with the API) as:

V = RAMONVolume;
V.setCutout(im);

Make sense?

Best,
Will

**Comment by rogerzou** [comment]
What's the best way to get in touch with him?
Thanks,
Roger

**Comment by wrgr** [comment]
Kunal Lillaney lillaney@jhu.edu

:)

Best,
Will

**Pull request merged**
